AquarioSite/Models/Dados.cs
namespace AquarioSite.Models
{
    public class Dados
    {
        public int Id { get; set; }

        public float Temperatura { get; set; }
        public float Tds { get; set; }
        public float Ph { get; set; }

        public bool IsVccAtivo { get; set; }

        public DateTime DataHora { get; set; }

        public Dados()
        {
            this.DataHora = DateTime.UtcNow;
        }
    }
}

AquarioSite/Models/ErrorViewModel.cs
namespace AquarioSite.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AquarioSite/Controllers/DadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AquarioSite.Data;
using AquarioSite.Models;
using Newtonsoft.Json;

namespace AquarioSite.Controllers
{
    public class DadosController : Controller
    {
        private readonly AquarioSiteContext _context;

        HttpClientHandler _clientHandler = new HttpClientHandler();

        Dados _oDados = new Dados();
        List<Dados> _ListDados = new List<Dados>();
        public DadosController(AquarioSiteContext context)
        {
            _clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            _context = context;
        }

        // GET: Dados
        public async Task<IActionResult> Index()
        {
            _ListDados = new List<Dados>();
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://grupoi.azurewebsites.net/api/dados"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    _ListDados = JsonConvert.DeserializeObject<List<Dados>>(apiResponse);

                }
            }
            return View(_ListDados.OrderByDescending(m => m.Id).Take(100));
            //return _context.Dados != null ?
            //                View(await _context.Dados.ToListAsync()) :
            //                Problem("Entity set 'AquarioSiteContext.Dados'  is null.");
        }

        // GET: Dados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //  if (id == null || _context.Dados == null)
            //   {
            //       return NotFound();
            //  }

            //   var dados = await _context.Dados
            //       .FirstOrDefaultAsync(m => m.Id == id);
            //    if (dados == null)
            //   {
            //        return NotFound();
            //    }
            _ListDados = new List<Dados>();
            using (var httpClient = new HttpClient(_clientHandler))
            {
                using (var response = await httpClient.GetAsync("https://grupoi.azurewebsites.net/api/dados"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    _ListDados = JsonConvert.DeserializeObject<List<Dados>>(apiResponse);

                }
            }
            _oDados = _ListDados.OrderByDescending(m => m.Id).FirstOrDefault();

            if (_oDados == null)
            {
                return NotFound();
            }else
            {
                if (_oDados.IsVccAtivo)
                    ViewBag.Power = true;
                else
                    ViewBag.Power = false;
                return View(_oDados);
            }
        }

        // GET: Dados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Temperatura,Tds,Ph,IsVccAtivo,DataHora")] Dados dados)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dados);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dados);
        }

        // GET: Dados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Dados == null)
            {
                return NotFound();
            }

            var dados = await _context.Dados.FindAsync(id);
            if (dados == null)
            {
                return NotFound();
            }
            return View(dados);
        }

        // POST: Dados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Temperatura,Tds,Ph,IsVccAtivo,DataHora")] Dados dados)
        {
            if (id != dados.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dados);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DadosExists(dados.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dados);
        }

        // GET: Dados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Dados == null)
            {
                return NotFound();
            }

            var dados = await _context.Dados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dados == null)
            {
                return NotFound();
            }

            return View(dados);
        }

        // POST: Dados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Dados == null)
            {
                return Problem("Entity set 'AquarioSiteContext.Dados'  is null.");
            }
            var dados = await _context.Dados.FindAsync(id);
            if (dados != null)
            {
                _context.Dados.Remove(dados);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DadosExists(int id)
        {
          return (_context.Dados?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AquarioSite/Controllers/HomeController.cs
using AquarioSite.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AquarioSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AquarioSite/Views/Dados/Create.cshtml
@model AquarioSite.Models.Dados

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Dados</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Temperatura" class="control-label"></label>
                <input asp-for="Temperatura" class="form-control" />
                <span asp-validation-for="Temperatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tds" class="control-label"></label>
                <input asp-for="Tds" class="form-control" />
                <span asp-validation-for="Tds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ph" class="control-label"></label>
                <input asp-for="Ph" class="form-control" />
                <span asp-validation-for="Ph" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVccAtivo" /> @Html.DisplayNameFor(model => model.IsVccAtivo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DataHora" class="control-label"></label>
                <input asp-for="DataHora" class="form-control" />
                <span asp-validation-for="DataHora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AquarioSite/Views/Dados/Delete.cshtml
@model AquarioSite.Models.Dados

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dados</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Temperatura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Temperatura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ph)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ph)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVccAtivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVccAtivo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataHora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataHora)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AquarioSite/Views/Dados/Details.cshtml
@model AquarioSite.Models.Dados

@{
    ViewData["Title"] = "Details";
}

<h1>Aquário Grupo I - Status</h1>
@if (ViewBag.Power == false)
{
    <script>alert("AQUÁRIO SEM ENERGIA!!!")</script> 
    <center><h1>AQUÁRIO SEM ENERGIA!!!!!</h1></center>
}
<div>
    <h4>Sensores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Temperatura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Temperatura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ph)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ph)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVccAtivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVccAtivo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataHora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataHora)
        </dd>
    </dl>
</div>
<div>
    <!--<a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |-->
    <a asp-action="Index">Voltar ao histórico</a>
</div>

AquarioSite/Views/Dados/Edit.cshtml
@model AquarioSite.Models.Dados

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Dados</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Temperatura" class="control-label"></label>
                <input asp-for="Temperatura" class="form-control" />
                <span asp-validation-for="Temperatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tds" class="control-label"></label>
                <input asp-for="Tds" class="form-control" />
                <span asp-validation-for="Tds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ph" class="control-label"></label>
                <input asp-for="Ph" class="form-control" />
                <span asp-validation-for="Ph" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVccAtivo" /> @Html.DisplayNameFor(model => model.IsVccAtivo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DataHora" class="control-label"></label>
                <input asp-for="DataHora" class="form-control" />
                <span asp-validation-for="DataHora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AquarioSite/Views/Dados/Index.cshtml
@model IEnumerable<AquarioSite.Models.Dados>

@{
    ViewData["Title"] = "Index";
}

<h1>Aquário - Grupo I - Histórico de Leitura</h1>
<br />
<h3><a asp-action="Details">Exibir leitura atual</a></h3>
<!--<p>
    <a asp-action="Create">Create New</a>
</p>-->
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Temperatura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tds)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ph)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsVccAtivo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataHora)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Temperatura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tds)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ph)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsVccAtivo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataHora)
            </td>
            <!-- <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td> -->
        </tr>
}
    </tbody>
</table>

AquarioSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem-vindo ao Aquário Grupo I</h1>
</div>

AquarioSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestor de Aquário</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AquarioSite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestor de Aquário</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dados" asp-action="Details">Atual</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dados" asp-action="Index">Histórico de leitura</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Gestor de Aquário - Grupo I
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>